//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTbl
    {
        public int RowId { get; set; }
        public string ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Type { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Qual { get; set; }
        public string Gender { get; set; }
        public string Nid { get; set; }
        public string Specl { get; set; }
        public string Salary { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Address { get; set; }
        public byte[] Image { get; set; }
    }
}
